#!/usr/bin/env bash
# Configures an ubuntu server as follows:   #       - localhost resolves to 127.0.0.2   #       - facebook.com resolves to 8.8.8.8
                                            cp /etc/hosts ~/etc/hosts.new               sed -e 's/127.*$/127.0.0.2 localhost\n8.8.8.8                                           facebook.com/' ~/hosts.new
cp -f ~/hosts.new /etc/hosts
