#!/bin/bash
# Server details (replace if necessary)
server_ip="54.174.106.133"
username="ubuntu"
ssh_key="~/.ssh/school"

# Connect to server using SSH with single-character flags
ssh -i "$ssh_key" $username@$server_ip

# Note: Script assumes the SSH key is not passphrase-protected

