#!/bin/env bash
#Name of the private key file
private_key="school"

#Number of bits for the RSA key pair
bits=4096

#Passphrase to protect the private key
passphrase="betty"

#Generate RSA key pair with the specified bits and passphrase
ssh-keygen -t rsa -b $bits -f "$private_key" -N "$passphrase"

echo "RSA key pair created successfully."

