#!/bin/bash
# Key details

key_name="school"
key_type="rsa"
key_bits=4096
passphrase="betty"

# Generate the key pair with passphrase protection
ssh-keygen -t $key_type -b $key_bits -f "$key_name" -N "$passphrase"
